Module2 task1
htmlacademy-adaptive/1944511-pink-25 pull request #2
Opened 2022-04-06 11:40 UTC by igorr28

2022-04-06 18:06 UTC, pavel-niukalo requested changes
Здесь лучше без фона экспортировать, фон будет тянуться, а вот рука будет фиксированной
![image](https://user-images.githubusercontent.com/52506235/162038809-3048b3c2-3c52-4bf1-936d-1f02d013e3eb.png)

2022-04-06 18:06 UTC, pavel-niukalo commented on source/img/icons/VK.svg
> +<svg width="18" height="11" viewBox="0 0 18 11" fill="none" xmlns="http://www.w3.org/2000/svg">
Название содержит заглавные буквы - не пройдет критерий единообразности

2022-04-06 18:06 UTC, pavel-niukalo commented on Readme.md
> +* Наставник: [Павел Нюкало](https://up.htmlacademy.ru/profession/frontender/13/adaptive/25/user/869225).
Это же делали в том задании?🤔
У тебя ветка `module2-task1` от обновленного `master`?

2022-04-06 18:06 UTC, pavel-nyukalo commented on source/index.html
> +        <div class="promo__download download">
Нужно проверить отступы (например `p` имеет 4 пробела от `section`, должно быть 2)

2022-04-06 18:06 UTC, pavel-nyukalo commented on source/index.html
> +            <a class="dowmload__link button buttom--primary" href="https://www.apple.com/ru/app-store/">
`buttoN buttoM--primary`

Так же надо поправить ошибки по [БЭМу](https://yoksel.github.io/html-tree/)
![image](https://user-images.githubusercontent.com/52506235/162039427-51ed1b7c-c9c0-46d2-9cab-f40f05e3eb72.png)

2022-04-07 05:36 UTC, igorr28 commented on Readme.md
> +* Наставник: [Павел Нюкало](https://up.htmlacademy.ru/profession/frontender/13/adaptive/25/user/869225).
Ну да я синхронизировал master. Правда гит  ругался почему-то.  Я файлы проверил вроде все верно. 
Для синхронизации нам 2 способа показали. В материалах к дз там сначала локальный репозиторий синхронизируешь, а потом push в свой удаленный. А на лайве там через гитхаб  fetch моего удаленного репозитория с репозиторием академии, а  потом pull в локальный.   Я по второму способу делал.

2022-04-07 05:36 UTC, igorr28 commented on source/index.html
> +            <a class="dowmload__link button buttom--primary" href="https://www.apple.com/ru/app-store/">
Исправил.
Генератор классная вещь, а то с этими черточками уже крыша едет

2022-04-07 05:39 UTC, igorr28 commented on source/img/icons/VK.svg
> +<svg width="18" height="11" viewBox="0 0 18 11" fill="none" xmlns="http://www.w3.org/2000/svg">
исправил

2022-04-07 06:10 UTC, igorr28 commented on source/index.html
> +        <div class="promo__download download">
Вроде исправил

2022-04-08 07:31 UTC, pavel-nyukalo commented on Readme.md
> +* Наставник: [Павел Нюкало](https://up.htmlacademy.ru/profession/frontender/13/adaptive/25/user/869225).
Просто странно, по идее, то что ты менял в первом задании не должно сюда подтянуться

2022-04-08 07:34 UTC, pavel-nyukalo approved these changes

2022-04-08 07:34 UTC, merged