Разметка внутренних страниц
htmlacademy-adaptive/1944511-pink-25 pull request #3
Opened 2022-04-11 17:27 UTC by igorr28

---
:mortar_board: [Разметка внутренних страниц](https://up.htmlacademy.ru/adaptive/25/user/1944511/tasks/3)

2022-04-13 05:46 UTC, pavel-nyukalo requested changes

2022-04-13 05:46 UTC, pavel-nyukalo commented on source/catalog.html
> +    </section>
Много `div`ов кажется излишним, во время стилизации попробуй от них избавиться, возможно получится миксованием например

2022-04-13 05:46 UTC, pavel-nyukalo commented on source/catalog.html
> +                <button class="card__like-button"></button>
Надо добавить описание кнопке, либо через скрытый элемент, либо через `aria-label`

2022-04-13 05:46 UTC, pavel-nyukalo commented on source/catalog.html
> +                <button class="card__like-button"></button>
Остальным тоже соответственно

2022-04-13 05:46 UTC, pavel-nyukalo commented on source/form.html
> +    </section>
Здесь так же про `div`. Сейчас можешь оставить, но во время стилизации попробуй сократить

2022-04-13 05:46 UTC, pavel-nyukalo commented on source/form.html
> +                  ФАМИЛИЯ:
Лучше оставить все единообразно, у нас весь текст написан в нижнем регистре (кроме первой буквы само собой). А в верхний регистр уже через `css` сделаем

2022-04-14 09:54 UTC, igorr28 commented on source/catalog.html
> +                <button class="card__like-button"></button>
исправил

2022-04-14 09:54 UTC, igorr28 commented on source/form.html
> +    </section>
исправил

2022-04-14 09:54 UTC, igorr28 commented on source/form.html
> +                  ФАМИЛИЯ:
исправил

2022-04-14 09:54 UTC, igorr28 commented on source/catalog.html
> +                <button class="card__like-button"></button>
исправил

2022-04-14 09:54 UTC, igorr28 commented on source/catalog.html
> +    </section>
Исправил

2022-04-15 06:00 UTC, pavel-nyukalo approved these changes

2022-04-15 06:00 UTC, merged