Module3 task1
htmlacademy-adaptive/1944511-pink-25 pull request #4
Opened 2022-04-20 16:00 UTC by igorr28

2022-04-20 17:21 UTC, pavel-nyukalo requested changes

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/base/button.scss
> +.button--tertiary {
В принципе для модификаторов можно использовать `&`, но это как рекомендация

```scss
button {
  ...
  &--primary {
    ...
  }
}
```

Преобразуется в конечном итоге как раз в два селектора как у тебя `.button {} .button--primary {}`

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/base/button.scss
> +.button {
На проверке могут не пропустить в том плане, что `.button` это у нас БЭМ-блок, и поэтому он должен лежать в папке `blocks`.

Но твое решение тоже адекватное, просто могут по критерию не пропустить

2022-04-20 17:21 UTC, pavel-niukalo commented on source/sass/base/common.scss
> +.page {
`.page` тоже является БЭМ-блоком -> так же в папку `blocks`

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/base/container.scss
> +.container {
+1

2022-04-20 17:21 UTC, pavel-niukalo commented on source/sass/base/index-title.scss
> +.index-title {
+1

2022-04-20 17:21 UTC, pavel-niukalo commented on source/sass/base/mixins.scss
> +}
С миксинами прямо хорошо 👍🏼

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/blocks/advantages.scss
> +  background-image: url("../../img/bg-advantages.svg");
Весь препроцессорный файл в конечном итоге будет собираться в обычный `css` и если посмотреть на `gulpfile`, то складываться он будет в `source/css`.  
По итогу имеем такую структуру:
```
source/
  css/
    style.css
  fonts/
  img/
```

Соответственно из `style.css` нам надо подняться на один уровень и обращаться к картинкам `../img`

2022-04-20 17:21 UTC, pavel-niukalo commented on source/sass/blocks/advantages.scss
> +}
Предлагаю все же модификаторы (псевдоселекторы, псевдоклассы тоже по критерию можно) писать через `&`. При просмотре файла сразу будет понятно, где элементы, а где модификаторы к ним

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/blocks/comments.scss
> +  line-height: 30px;
Как предложение, можно еще вынести какие-то шрифтовые параметры в миксины.  
Например, у нас на работе есть набор миксинов по типографии:
```scss
@mixin h1 {
  font-size: 18px;
  font-weight: 700;
  line-height: 24px;
}
// и тд
```

Но это не ошибка, просто предложение

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/blocks/form.scss
> +.form__input::placeholder {
Как уже писал, псевдоклассы тоже можно через `&`

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/blocks/intro-catalog.scss
> +  background-image: url("../../img/promo-bg.jpg");
Здесь тоже не забудь поправить

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/blocks/intro-form.scss
> +  background-image: url("../../img/promo-bg.jpg");
+1

2022-04-20 17:21 UTC, pavel-niukalo commented on source/sass/blocks/map.scss
> +  background-image: url("../../img/bg-map.svg");
+1

2022-04-20 17:21 UTC, pavel-niukalo commented on source/sass/blocks/promo.scss
> +  background-image: url("../../img/promo.png"), url("../../img/promo-bg.jpg");
+1

2022-04-20 17:21 UTC, pavel-nyukalo commented on source/sass/blocks/tariffs.scss
> +  background-image: url("../../img/bg-tariffs.svg");
+1

2022-04-20 19:38 UTC, igorr28 commented on source/sass/base/button.scss
> +.button {
Исправил

2022-04-20 19:38 UTC, igorr28 commented on source/sass/base/common.scss
> +.page {
исправил

2022-04-20 19:38 UTC, igorr28 commented on source/sass/base/container.scss
> +.container {
исправил

2022-04-20 19:39 UTC, igorr28 commented on source/sass/base/index-title.scss
> +.index-title {
исправил

2022-04-20 19:39 UTC, igorr28 commented on source/sass/blocks/advantages.scss
> +  background-image: url("../../img/bg-advantages.svg");
исправил

2022-04-20 19:41 UTC, igorr28 commented on source/sass/blocks/intro-catalog.scss
> +  background-image: url("../../img/promo-bg.jpg");
исправил

2022-04-20 19:41 UTC, igorr28 commented on source/sass/blocks/intro-form.scss
> +  background-image: url("../../img/promo-bg.jpg");
исправил

2022-04-20 19:42 UTC, igorr28 commented on source/sass/blocks/map.scss
> +  background-image: url("../../img/bg-map.svg");
тоже

2022-04-20 19:42 UTC, igorr28 commented on source/sass/blocks/promo.scss
> +  background-image: url("../../img/promo.png"), url("../../img/promo-bg.jpg");
+

2022-04-20 19:42 UTC, igorr28 commented on source/sass/blocks/tariffs.scss
> +  background-image: url("../../img/bg-tariffs.svg");
+

2022-04-20 19:50 UTC, igorr28 commented on source/sass/base/button.scss
> +.button--tertiary {
Так вложенности вроде как запретили. Хотя возможно я что-то путаю. Вроде как на 3 лайве и где-то в чате проскакивало  что есть такой критерий.  Я и не стал рисковать и использовать их. 
В общем пока под вопросом.  Подскажи если точно знаешь есть ли ограничения на них?

2022-04-20 19:51 UTC, igorr28 commented on source/sass/base/mixins.scss
> +}
:)

2022-04-20 19:52 UTC, igorr28 commented on source/sass/blocks/advantages.scss
> +}
я тоже за, но по ним пока вопрос

2022-04-20 19:59 UTC, igorr28 commented on source/sass/blocks/comments.scss
> +  line-height: 30px;
Ну это со временем. Пока не везде удается улавливать эти моменты

2022-04-20 20:00 UTC, igorr28 commented on source/sass/blocks/form.scss
> +.form__input::placeholder {
?

2022-04-21 12:25 UTC, pavel-nyukalo commented on source/sass/base/button.scss
> +.button--tertiary {
Про `&` вот [критерий](https://up.htmlacademy.ru/adaptive/25/criteries#d11), что его можно использовать, и в [критерии](https://up.htmlacademy.ru/adaptive/25/criteries#d10) про вложенность он тоже фигурирует.

![image](https://user-images.githubusercontent.com/52506235/164457427-3ca1eb15-8dc1-4e99-a7f9-17a3071e188d.png)

2022-04-21 12:30 UTC, pavel-niukalo approved these changes

2022-04-21 12:30 UTC, merged