Module4 task1
htmlacademy-adaptive/1944511-pink-25 pull request #5
Opened 2022-04-24 17:54 UTC by igorr28

2022-04-25 15:05 UTC, pavel-nyukalo requested changes

2022-04-25 15:05 UTC, pavel-niukalo commented on source/index.html
> +        </div class="container">
Класс на закрывающем теге - ошибка валидации

2022-04-25 15:05 UTC, pavel-niukalo commented on source/sass/blocks/button-close.scss
> +.main-header--active .button-close {
У нас есть `main-header__button-close`, вот тут лучше ее использовать и перенести в `main-header.scss`, чтобы в стилях `main-header` были только стили для `main-header`, а в `button-close.scss` только для `button-close`

2022-04-25 15:05 UTC, pavel-niukalo commented on source/sass/blocks/button-open.scss
> +.main-header--active .button-open {
Тут тоже аналогично, надо перенести в `main-header.scss` и использовать `main-header__open`

2022-04-25 15:05 UTC, pavel-nyukalo commented on source/sass/blocks/main-menu.scss
> +.main-header--active .main-menu {
Аналогично про `main-header` и `main-header__menu`

2022-04-25 15:05 UTC, pavel-niukalo commented on source/sass/blocks/main-menu.scss
> +.main-header--active .main-menu__link {
Тоже надо вынести

2022-04-25 18:05 UTC, igorr28 commented on source/index.html
> +        </div class="container">
исправил

2022-04-25 18:05 UTC, igorr28 commented on source/sass/blocks/button-close.scss
> +.main-header--active .button-close {
исправил

2022-04-25 18:05 UTC, igorr28 commented on source/sass/blocks/button-open.scss
> +.main-header--active .button-open {
+

2022-04-25 18:05 UTC, igorr28 commented on source/sass/blocks/main-menu.scss
> +.main-header--active .main-menu__link {
+

2022-04-27 05:29 UTC, pavel-nyukalo approved these changes

2022-04-27 05:29 UTC, merged