Module4 task2
htmlacademy-adaptive/1944511-pink-25 pull request #6
Opened 2022-04-28 17:49 UTC by igorr28

2022-04-29 16:54 UTC, pavel-nyukalo requested changes
В целом все отлично, единственное надо скролл горизонтальный поправить

2022-04-29 16:54 UTC, pavel-nyukalo commented on source/sass/blocks/form-post.scss
>  .form-post__range-list {
Могут придраться к скроллу
![image](https://user-images.githubusercontent.com/52506235/165988630-3d80a488-e85a-4293-97bb-289db4d6faa1.png)

2022-04-29 19:02 UTC, igorr28 commented on source/sass/blocks/form-post.scss
>  .form-post__range-list {
Исправил

2022-05-02 05:54 UTC, pavel-nyukalo approved these changes

2022-05-02 05:54 UTC, merged