добавляет адаптив мелких блоков главной страницы
htmlacademy-adaptive/1944511-pink-25 pull request #7
Opened 2022-05-02 14:57 UTC by igorr28

2022-05-04 16:16 UTC, pavel-nyukalo requested changes
`textarea` и `input` надо тоже дать `font-family: inherit`, чтобы шрифты подтянули
![image](https://user-images.githubusercontent.com/52506235/166725260-7597eb55-f4af-49be-974c-f04927511531.png)

2022-05-04 16:16 UTC, pavel-niukalo commented on source/sass/blocks/advantages.scss
> +    // padding-right: 24px;
Если не нужны то лучше удалить, чтобы не засорять код

2022-05-04 16:16 UTC, pavel-niukalo commented on source/sass/blocks/main-menu.scss
> +.main-menu__link---current::after {
Лишняя `-`, поэтому полоска не отображается

2022-05-04 16:16 UTC, pavel-niukalo commented on source/sass/blocks/map.scss
> +  width: 100%;
`iframe` по-умолчанию имеет `box-sizing: content-box` и рамку в 2рх. Поэтому ширина в 100% создает горизонтальный скролл. Либо рамку убрать, либо `box-sizing` поменять

2022-05-04 16:16 UTC, pavel-nyukalo commented on source/sass/blocks/table.scss
> +
Напишу здесь, если у `tariffs__table-wrap` убрать фиксированную ширину, дать ему флекс и `justify-content` по центру, то можно добить эффекта 'открытия' таблицы при изменении ширины экрана. (Надо еще запретить таблице сжиматься и убрать `transform`)
Было:
![image](https://user-images.githubusercontent.com/52506235/166724245-c96cf240-8ff2-454e-a061-6004a285a8c1.png)

Стало:
![image](https://user-images.githubusercontent.com/52506235/166724219-38f1aabc-09f6-480b-8aa7-5db1a60b945a.png)

2022-05-05 09:44 UTC, igorr28 commented on source/sass/blocks/advantages.scss
> +    // padding-right: 24px;
+

2022-05-05 09:44 UTC, igorr28 commented on source/sass/blocks/main-menu.scss
> +.main-menu__link---current::after {
+

2022-05-05 09:44 UTC, igorr28 commented on source/sass/blocks/map.scss
> +  width: 100%;
+

2022-05-05 09:44 UTC, igorr28 commented on source/sass/blocks/table.scss
> +
+

2022-05-06 17:21 UTC, pavel-nyukalo approved these changes

2022-05-06 17:22 UTC, merged